02-WEB-APIs/First_API_Django/onlinestore/onlinestore/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("products.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

02-WEB-APIs/First_API_Django/onlinestore/products/urls.py
from django.urls import path
from .views import product_list, product_detail, manufacturer_list, manufacturer_detail

app_name = "products"
urlpatterns = [
    path("products/", product_list, name="product-list"),
    path("products/<int:pk>/", product_detail, name="product-detail"),
    path("manufacturers/", manufacturer_list, name="manufacturer-list"),
    path("manufacturers/<int:pk>/", manufacturer_detail,
         name="manufacturer-detail"),
]

02-WEB-APIs/First_API_Django/onlinestore/products/models.py
from django.db import models


class Manufacturer(models.Model):
    name = models.CharField(max_length=120)
    location = models.CharField(max_length=120)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    manufacturer = models.ForeignKey(
        Manufacturer, on_delete=models.CASCADE, related_name="products")
    name = models.CharField(max_length=120)
    description = models.TextField(blank=True, null=True)
    photo = models.ImageField(blank=True, null=True)
    price = models.FloatField()
    shipping_cost = models.FloatField()
    quantity = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.name

02-WEB-APIs/First_API_Django/onlinestore/products/views.py
from django.http import JsonResponse
from .models import Product, Manufacturer


def product_list(request):
    products = Product.objects.all()  # [:30]
    data = {"products": list(products.values())}
    response = JsonResponse(data)
    return response


def product_detail(request, pk):
    try:
        product = Product.objects.get(pk=pk)
        data = {"product": {
            "name": product.name,
            "manufacturer": product.manufacturer.name,
            "description": product.description,
            "photo": product.photo.url,
            "price": product.price,
            "shipping_cost": product.shipping_cost,
            "quantity": product.quantity,
        }}
        response = JsonResponse(data)
    except Product.DoesNotExist:
        response = JsonResponse({
            "error": {

                "code": 404,
                "message": "Product not found!"
            }
        }, status=404)

    return response


def manufacturer_list(request):
    manufacturers = Manufacturer.objects.filter(active=True)
    data = {"manufacturers": list(manufacturers.values())}
    response = JsonResponse(data)
    return response


def manufacturer_detail(request, pk):
    try:
        manufacturer = Manufacturer.objects.get(pk=pk)
        products = manufacturer.products.values()
        data = {"manufacturer": {
            "name": manufacturer.name,
            "location": manufacturer.location,
            "active": manufacturer.active,
            "products": list(products.values())
        }}
        response = JsonResponse(data)
    except:
        response = JsonResponse({
            "error": {
                "code": 404,
                "message": "Manufacturer not found!"
            }
        }, status=404)

    return response


# Create your views here.
# from django.views.generic.detail import DetailView
# from django.views.generic.list import ListView

# class ProductDetailView(DetailView):
#     model = Product
#     template_name = "products/product_detail.html"


# class ProductListView(ListView):
#     model = Product
#     template_name = "products/product_list.html"

02-WEB-APIs/First_API_Django/onlinestore/products/templates/products/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ object.name }}</title>
</head>
<body>
    <p>Product: {{ object.name }}</p>
    <p>Manufacturer: {{ object.manufacturer }}</p>
    <p>Quantity: {{ object.quantity }}</p>
    <p>Description: {{ object.description }}</p>
    <p>Price: {{ object.price }}</p>
    <p>Shipping Cost: $ {{ object.shipping_cost }}</p>

    <img src="{{ object.photo.url }}" alt="Product Photo">
</body>
</html>

02-WEB-APIs/First_API_Django/onlinestore/products/templates/products/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product List</title>
</head>
<body>
    {% for object in object_list %}
        <p>Product: <a href="{% url 'products:product-detail' object.id%}">{{ object.name }}</a></p>
        <p>Manufacturer: {{ object.manufacturer }}</p>
        <p>Price: {{ object.price }}</p>
    {% endfor %}
</body>
</html>